name: tranquilo-pres

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.10
  - pip

  # Dependencies
  - pandas
  - numpy
  - scipy
  - jupyterlab
  - ipython
  - seaborn
  - plotly
  - bokeh
  - sqlalchemy
  - numba
  - joblib
  - nlopt
  - click
  - cloudpickle
  - fuzzywuzzy
  - pybaum

  # Misc Start
  - setuptools_scm
  - toml
  - pytask<0.4
  - black
  - nb_black
  - pre-commit
  - pdbpp
  - pytest
  - pytest-cov
  - pytest-xdist
  # Misc End

  - pip:
    - black
    - blackcellmagic
    - kaleido

    # install this project locally
    - -e .

    # either install the most recent version of tranquilo from github, or clone the
    # repository to the parent folder and install in editable mode
    - -e ../../tranquilo
    # - git+https://github.com/OpenSourceEconomics/tranquilo

    # install most recent versions of estimagic
    - git+https://github.com/OpenSourceEconomics/estimagic

    # install altered version of dfols and pybobyqa that allows us to capture benchmark
    # results
    - git+https://github.com/mpetrosian/dfols
    - git+https://github.com/mpetrosian/pybobyqa
