name: tranquilo-dev

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.10
  - pip

  # Dependencies
  - pandas
  - numpy
  - scipy
  - jupyterlab
  - ipython
  - seaborn
  - plotly
  - bokeh
  - sqlalchemy
  - numba
  - joblib
  - nlopt
  - click
  - cloudpickle
  - fuzzywuzzy
  - pybaum

  # Misc Start
  - black
  - nb_black
  - pdbpp
  - pre-commit
  - pytask >=0.2.3
  - pytest
  - pytest-cov
  - pytest-xdist
  - sphinx
  - setuptools_scm
  - toml
  # Misc End

  - pip:
    - black
    - blackcellmagic
    - kaleido
    - snakemd

    # local installations
    - -e .
    - -e ../estimagic
    - -e ../dfols
    - -e ../pybobyqa
    - -e ../tranquilo
